fix: fix pipleine 4

diff --git a/.github/workflows/backend-ci.yaml b/.github/workflows/backend-ci.yaml
--- a/.github/workflows/backend-ci.yaml
+++ b/.github/workflows/backend-ci.yaml
@@ -7,19 +7,6 @@ on:
     branches: [ main,release, develop ]
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up JDK 17
-        uses: actions/setup-java@v2
-        with:
-          java-version: '11'
-          distribution: 'adopt'
-      - name: Build with Maven
-        run: mvn clean install
-
   test:
     runs-on: ubuntu-latest
     steps:
@@ -30,4 +17,9 @@ jobs:
           java-version: '17'
           distribution: 'adopt'
       - name: Run Tests with Maven
-        run: mvn test
+        run: |
+          mvn test
+          if [ $? -ne 0 ]; then
+            echo "Tests failed"
+            exit 1
+          fi
